### ISSUE TITLE
Add possibility to validate other methods of input, like JSON data in the request body

### ISSUE THREAD

**Issue by tneumueller** [gostalt/validate#9]

**Comment by tmus** [comment]
Hey @tneumueller, it's a nice idea, but I'd rather keep this library focused on validating a request form. However, it is definitely a common use case to want to validate JSON in the body.

The best way would probably be to create some sort of middleware that is ran before the validation, that reads the body and adds it to the request's Form field:

```go
r.ParseForm()

body, err := ioutil.ReadAll(r.Body)

values := make(map[string]string)
json.Unmarshal(body, &values)

for k, v := range values {
	r.Form.Add(k, v)
}
```

Then, you can run the validation on the request body as normal.
